@echo off
echo Deteniendo todos los procesos de Node.js...
taskkill /F /IM node.exe 2>nul

echo Esperando 2 segundos...
timeout /t 2 /nobreak >nul

echo Eliminando cache de Next.js...
if exist .next rmdir /s /q .next

echo Esperando 2 segundos...
timeout /t 2 /nobreak >nul

echo Iniciando servidor de desarrollo...
npm run dev
